# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Post Notes' do
  use_frameworks!

  # Pods for Post Notes
  pod 'Firebase', '3.11'
  pod 'FirebaseAuth', '3.1.0'
  pod 'RealmSwift', '2.1.2'
end
